In [1]:
pip install mysql-connector-python

   ---------------------------------------- 0.0/16.1 MB ? eta -:--:--
    --------------------------------------- 0.3/16.1 MB ? eta -:--:--
   --- ------------------------------------ 1.3/16.1 MB 4.8 MB/s eta 0:00:04
   ----- ---------------------------------- 2.1/16.1 MB 4.3 MB/s eta 0:00:04
   ------- -------------------------------- 2.9/16.1 MB 4.5 MB/s eta 0:00:03
   ----------- ---------------------------- 4.7/16.1 MB 5.5 MB/s eta 0:00:03
   -------------- ------------------------- 5.8/16.1 MB 5.3 MB/s eta 0:00:02
   ---------------- ----------------------- 6.8/16.1 MB 5.4 MB/s eta 0:00:02
   --------------------- ------------------ 8.7/16.1 MB 5.8 MB/s eta 0:00:02
   -------------------------- ------------- 10.5/16.1 MB 6.3 MB/s eta 0:00:01
   ------------------------------- -------- 12.8/16.1 MB 6.7 MB/s eta 0:00:01
   ------------------------------------- -- 14.9/16.1 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------- 16.1/16.1 MB 7.1 MB/s eta 0:00:00
Note: you

In [7]:
import mysql.connector


In [11]:
# Importing module
import mysql.connector

# Creating connection object
mydb = mysql.connector.connect(
	host = "localhost",
	user = "root",
	password = "root"
)

# Printing the connection object
print(mydb)

In [15]:
import mysql.connector  
#Create the connection object   
myconn = mysql.connector.connect(host = "localhost", user = "root",passwd = "root")  
  
#printing the connection object   
print(myconn)   
  
#creating the cursor object  
cur = myconn.cursor()  
  
print(cur)  

CMySQLCursor: (Nothing executed yet)


In [17]:
#creating the cursor object  
cur = myconn.cursor()  
  
try:  
    dbs = cur.execute("show databases")  
except:  
    myconn.rollback()  
for x in cur:  
    print(x)  
myconn.close()

('customer_orders',)
('information_schema',)
('mysql',)
('performance_schema',)
('sys',)


In [34]:
import mysql.connector

mydb = mysql.connector.connect(
	host = "localhost",
	user = "root",
	password = "root",
    database="customer_orders"
)

mycursor = mydb.cursor()

# Creating a table called 'STUDENT' in the
# 'mynewdatabase' database
mycursor.execute("CREATE SCHEMA IF NOT EXISTS CUSTOMER_ORDERS")

In [1]:
import numpy as np
a=np.array([7,9,9,2])
b=np.array([(7,9,9,2),(16,11,9,6)])
print(a.ndim)
print(a.itemsize)
print(a.dtype)
print(a.size*a.itemsize)
print(a.size)

1
4
int32
16
4


In [3]:
b=np.array([(7,9,9,2),(16,11,9,6)])
print(b)
b=b.reshape(4,2)
print(b)

[[ 7  9  9  2]
 [16 11  9  6]]
[[ 7  9]
 [ 9  2]
 [16 11]
 [ 9  6]]


In [5]:
b=np.array([(7,9,9,2),(11,16,9,9)])
print(b[0,2])
print(b[0:,2])

9
[9 9]


In [9]:
e=np.array([3,44,3,3,4,2,89])
print(e.min())
print(e.max())
print(e.sum())

2
89
148


In [11]:
a=np.array([7,9,9,2])
b=np.array([(7,9,9,2),(16,11,9,6)])
print(b.sum(axis=0))
print(b.sum(axis=1))
print(np.sqrt(a))
print(np.std(a))
print(np.exp(a))
print(np.log(a))
print(np.log10(a))

[23 20 18  8]
[27 42]
[2.64575131 3.         3.         1.41421356]
2.8613807855648994
[1.09663316e+03 8.10308393e+03 8.10308393e+03 7.38905610e+00]
[1.94591015 2.19722458 2.19722458 0.69314718]
[0.84509804 0.95424251 0.95424251 0.30103   ]


In [13]:
b=np.array([(7,9,9,2),(16,11,9,6)])
f=np.array([(1,2,3,4),(5,6,7,8)])
print(np.vstack((b,f)))
print(np.hstack((b,f)))
print(b.ravel())

[[ 7  9  9  2]
 [16 11  9  6]
 [ 1  2  3  4]
 [ 5  6  7  8]]
[[ 7  9  9  2  1  2  3  4]
 [16 11  9  6  5  6  7  8]]
[ 7  9  9  2 16 11  9  6]


In [17]:
threeDarray=np.array([[[1,2,3],[4,5,6]],[[-1,-2,-3],[-4,-5,-6]]])
print(threeDarray)

[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]


In [19]:
print(threeDarray[1,0])

[-1 -2 -3]


In [32]:
print(threeDarray)

[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]


In [34]:
zeros=np.zeros(5)
print(zeros)


[0. 0. 0. 0. 0.]


In [46]:
matrix1=np.array([[1,2,3],[4,5,6],[1,2,2]])
matrix2=np.array([[3,6,1],[8,5,1],[3,4,1]])
print(np.matmul(matrix1,matrix2))

[[28 28  6]
 [70 73 15]
 [25 24  5]]


In [56]:
marks=np.array([[-1,2,3],[1,2,2],[1,3,4],[4,5,6]])
print(marks.min())
print(marks.sum())
print(marks.std())

-1
32
1.8408935028645435


In [64]:
matrix1=np.array([[1,2,3],[4,5,6],[1,2,2]])
matrix2=np.array([[3,6,1],[8,5,1],[3,4,1]])
print(np.add(matrix1,matrix2))

[[ 4  8  4]
 [12 10  7]
 [ 4  6  3]]


In [73]:
marks=np.array([[-1,2,3],[1,2,2],[1,3,4],[4,5,6]]) #axis=1 means row
print(marks.min(axis=1))
print(marks.max(axis=1))
print(marks.sum(axis=1))
print(marks.mean(axis=1))
print(marks.std(axis=1))

[-1  1  1  4]
[3 2 4 6]
[ 4  5  8 15]
[1.33333333 1.66666667 2.66666667 5.        ]
[1.69967317 0.47140452 1.24721913 0.81649658]


In [75]:
marks=np.array([[-1,2,3],[1,2,2],[1,3,4],[4,5,6]]) #axis=0 means columnwise
print(marks.min(axis=0))
print(marks.max(axis=0))
print(marks.sum(axis=0))
print(marks.mean(axis=0))
print(marks.std(axis=0))

[-1  2  2]
[4 5 6]
[ 5 12 15]
[1.25 3.   3.75]
[1.78535711 1.22474487 1.47901995]


In [93]:
new_array=np.array([1,2,3])
x=np.append([[1,2,3],[4,5,6]],[[7,8,9],new_array],axis=0)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [95]:
np.transpose(x) #transpose operation

array([[1, 4, 7, 1],
       [2, 5, 8, 2],
       [3, 6, 9, 3]])

In [101]:
x.T #transpose

array([[1, 4, 7, 1],
       [2, 5, 8, 2],
       [3, 6, 9, 3]])

In [107]:
#boolean indexing
arr=np.arange(7)
print(arr)

[0 1 2 3 4 5 6]


In [109]:
arr>4

array([False, False, False, False, False,  True,  True])

In [111]:
arr[arr>4]

array([5, 6])

In [117]:
#reshaping array
array=np.arange(12)

In [119]:
array.shape=(3,4)

In [121]:
np.arange(12).reshape((2,3,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [123]:
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [127]:
#generating random values
np.random.rand(5)

array([0.48415842, 0.48085699, 0.93664923, 0.85583368, 0.11614201])

In [129]:
np.random.randint(10,20,(5,5))

array([[17, 17, 17, 10, 12],
       [17, 10, 15, 16, 14],
       [16, 11, 12, 11, 17],
       [19, 14, 16, 19, 16],
       [19, 19, 18, 16, 14]])

In [131]:
np.random.randint(10,20,(5,5,5))

array([[[17, 15, 19, 14, 17],
        [12, 10, 14, 12, 10],
        [12, 17, 15, 10, 14],
        [17, 10, 13, 17, 17],
        [16, 16, 17, 17, 15]],

       [[11, 14, 12, 14, 13],
        [19, 19, 15, 18, 17],
        [14, 18, 16, 18, 13],
        [18, 12, 12, 10, 15],
        [10, 10, 13, 18, 10]],

       [[14, 12, 11, 16, 10],
        [17, 15, 11, 19, 14],
        [15, 10, 12, 18, 18],
        [10, 18, 16, 12, 17],
        [10, 14, 19, 16, 12]],

       [[11, 12, 19, 12, 12],
        [15, 15, 11, 11, 17],
        [15, 15, 18, 14, 12],
        [16, 18, 11, 10, 18],
        [17, 10, 15, 14, 12]],

       [[11, 17, 16, 16, 13],
        [19, 12, 18, 19, 14],
        [13, 11, 14, 13, 14],
        [17, 17, 19, 14, 18],
        [16, 10, 15, 18, 18]]])

In [133]:
np.random.randint(10,20,(3,2,1,1))

array([[[[14]],

        [[14]]],


       [[[14]],

        [[18]]],


       [[[10]],

        [[11]]]])

In [135]:
np.random.randint(10,20,(0,0,0,0))

array([], shape=(0, 0, 0, 0), dtype=int32)

In [141]:
letters=list('aeiou')
print(letters)

['a', 'e', 'i', 'o', 'u']


In [145]:
np.random.choice(letters,5,p=[0.4,0.3,0.1,0.1,0.1])

array(['a', 'e', 'a', 'e', 'e'], dtype='<U1')

In [149]:
array=np.random.randint(10,20,(5,5))
np.save('array_file',array)

In [153]:
array2=np.load('array_file.npy')
print(array2)

[[12 17 16 17 14]
 [18 17 17 12 13]
 [10 12 14 14 10]
 [14 10 19 19 18]
 [16 16 14 17 19]]
